package protocol;

public enum MessageType {
    REGISTER,
    REGISTERED,
    CHANGE_PASSWORD,
    PASSWORD_CHANGED,
    LOGIN,
    LOGIN_TOKEN,
    AUTHENTICATED,
    AUTHENTICATED_TOKEN,
    JOIN_SIMPLE_QUEUE,
    JOIN_RANKED_QUEUE,
    QUEUED,
    RESUME_QUEUE,
    RESUME_GAME,
    START_GAME,
    END_GAME,
    ERROR
}


